def gsub_english_name_to_persian(s)
  s.sub!(/\[\[w:(English language\|English)\]\]/i, '[[w:fa:زبان انگلیسی|انگلیسی]]')
  s.sub!(/\[\[w:(German language\|German)\]\]/i, '[[w:fa:زبان آلمانی|آلمانی]]')
  s.sub!(/\[\[w:(French language\|French)\]\]/i, '[[w:fa:زبان فرانسوی|فرانسوی]]')
  s.sub!(/\[\[w:(Polish language\|Polish)\]\]/i, '[[w:fa:زبان لهستانی|لهستانی]]')
  s.sub!(/\[\[w:(Italian language\|Italian)\]\]/i, '[[w:fa:زبان ایتالیایی|ایتالیایی]]')
  s.sub!(/\[\[w:(Japanese language\|Japanese)\]\]/i, '[[w:fa:زبان ژاپنی|ژاپنی]]')
  s.sub!(/\[\[w:(Spanish language\|Spanish)\]\]/i, '[[w:fa:زبان اسپانیایی|اسپانیایی]]')
  s.sub!(/\[\[w:(Russian language\|Russian)\]\]/i, '[[w:fa:زبان روسی|روسی]]')
  s.sub!(/\[\[w:(Portuguese language\|Portuguese)\]\]/i, '[[w:fa:زبان پرتغالی|پرتغالی]]')
  s.sub!(/\[\[w:(Dutch language\|Dutch)\]\]/i, '[[w:fa:زبان هلندی|هلندی]]')
  s.sub!(/\[\[w:(Swedish language\|Swedish)\]\]/i, '[[w:fa:زبان سوئدی|سوئدی]]')
  s.sub!(/\[\[w:(Chinese language\|Chinese)\]\]/i, '[[w:fa:زبان چینی|چینی]]')
  s.sub!(/\[\[w:(Catalan language\|Catalan)\]\]/i, '[[w:fa:زبان کاتالان|کاتالان]]')
  s.sub!(/\[\[w:(Ukrainian language\|Ukrainian)\]\]/i, '[[w:fa:زبان اوکراینی|اوکراینی]]')
  s.sub!(/\[\[w:(Finnish language\|Finnish)\]\]/i, '[[w:fa:زبان فنلاندی|فنلاندی]]')
  s.sub!(/\[\[w:(Vietnamese language\|Vietnamese)\]\]/i, '[[w:fa:زبان ویتنامی|ویتنامی]]')
  s.sub!(/\[\[w:(Czech language\|Czech)\]\]/i, '[[w:fa:زبان چکی|چکی]]')
  s.sub!(/\[\[w:(Hungarian language\|Hungarian)\]\]/i, '[[w:fa:زبان مجاری|مجاری]]')
  s.sub!(/\[\[w:(Korean language\|Korean)\]\]/i, '[[w:fa:زبان کره‌ای|کره‌ای]]')
  s.sub!(/\[\[w:(Romanian language\|Romanian)\]\]/i, '[[w:fa:زبان رومانیایی|رومانیایی]]')
  s.sub!(/\[\[w:(Indonesian language\|Indonesian)\]\]/i, '[[w:fa:زبان اندونزیایی|اندونزیایی]]')
  s.sub!(/\[\[w:(Turkish language\|Turkish)\]\]/i, '[[w:fa:زبان ترکی استانبولی|ترکی استانبولی]]')
  s.sub!(/\[\[w:(Danish language\|Danish)\]\]/i, '[[w:fa:زبان دانمارکی|دانمارکی]]')
  s.sub!(/\[\[w:(Arabic language\|Arabic)\]\]/i, '[[w:fa:زبان عربی|عربی]]')
  s.sub!(/\[\[w:(Esperanto language\|Esperanto)\]\]/i, '[[w:fa:زبان اسپرانتو|اسپرانتو]]')
  s.sub!(/\[\[w:(Serbian language\|Serbian)\]\]/i, '[[w:fa:زبان صربی|صربی]]')
  s.sub!(/\[\[w:(Lithuanian language\|Lithuanian)\]\]/i, '[[w:fa:زبان لیتوانیایی|لیتوانیایی]]')
  s.sub!(/\[\[w:(Slovak language\|Slovak)\]\]/i, '[[w:fa:زبان اسلواکیایی|اسلواکیایی]]')
  s.sub!(/\[\[w:(Persian language\|Persian)\]\]/i, '[[w:fa:زبان فارسی|فارسی]]')
  s.sub!(/\[\[w:(Volap\&\#252\;k language\|Volap\&\#252\;k)\]\]/i, '[[w:fa:زبان ولاپوک|ولاپوک]]')
  s.sub!(/\[\[w:(Hebrew language\|Hebrew)\]\]/i, '[[w:fa:زبان عبری|عبری]]')
  s.sub!(/\[\[w:(Malay language\|Malay)\]\]/i, '[[w:fa:زبان مالایی|مالایی]]')
  s.sub!(/\[\[w:(Bulgarian language\|Bulgarian)\]\]/i, '[[w:fa:زبان بلغاری|بلغاری]]')
  s.sub!(/\[\[w:(Slovenian language\|Slovenian)\]\]/i, '[[w:fa:زبان اسلوونیایی|اسلوونیایی]]')
  s.sub!(/\[\[w:(Croatian language\|Croatian)\]\]/i, '[[w:fa:زبان کرواتی|کرواتی]]')
  s.sub!(/\[\[w:(Estonian language\|Estonian)\]\]/i, '[[w:fa:زبان استونیایی|استونیایی]]')
  s.sub!(/\[\[w:(Hindi language\|Hindi)\]\]/i, '[[w:fa:زبان هندی|هندی]]')
  s.sub!(/\[\[w:(Galician language\|Galician)\]\]/i, '[[w:fa:زبان گالیسی|گالیسی]]')
  s.sub!(/\[\[w:(Thai language\|Thai)\]\]/i, '[[w:fa:زبان تایلندی|تایلندی]]')
  s.sub!(/\[\[w:(Basque language\|Basque)\]\]/i, '[[w:fa:زبان باسکی|باسکی]]')
  s.sub!(/\[\[w:(Greek language\|Greek)\]\]/i, '[[w:fa:زبان یونانی|یونانی]]')
  s.sub!(/\[\[w:(Azerbaijani language\|Azerbaijani)\]\]/i, '[[w:fa:زبان ترکی آذربایجانی|ترکی آذربایجانی]]')
  s.sub!(/\[\[w:(Latin language\|Latin)\]\]/i, '[[w:fa:زبان لاتین|لاتین]]')
  s.sub!(/\[\[w:(Tagalog language\|Tagalog)\]\]/i, '[[w:fa:زبان تاگالوگ|تاگالوگ]]')
  s.sub!(/\[\[w:(Telugu language\|Telugu)\]\]/i, '[[w:fa:زبان تلگو|تلگو]]')
  s.sub!(/\[\[w:(Georgian language\|Georgian)\]\]/i, '[[w:fa:زبان گرجی|گرجی]]')
  s.sub!(/\[\[w:(Macedonian language\|Macedonian)\]\]/i, '[[w:fa:زبان مقدونی|مقدونی]]')
  s.sub!(/\[\[w:(Serbo\-Croatian language\|Serbo\-Croatian)\]\]/i, '[[w:fa:زبان صربی کرواتی|صربی کرواتی]]')
  s.sub!(/\[\[w:(Breton language\|Breton)\]\]/i, '[[w:fa:زبان برتون|برتون]]')
  s.sub!(/\[\[w:(Belarusian \(Tara\&\#353\;kievica\) language\|Belarusian \(Tara\&\#353\;kievica\))\]\]/i, '[[w:fa:زبان بلاروسی|بلاروسی]]')
  s.sub!(/\[\[w:(Latvian language\|Latvian)\]\]/i, '[[w:fa:زبان لتونیایی|لتونیایی]]')
  s.sub!(/\[\[w:(Marathi language\|Marathi)\]\]/i, '[[w:fa:زبان مراتی|مراتی]]')
  s.sub!(/\[\[w:(Javanese language\|Javanese)\]\]/i, '[[w:fa:زبان جاوه‌ای|جاوه‌ای]]')
  s.sub!(/\[\[w:(Luxembourgish language\|Luxembourgish)\]\]/i, '[[w:fa:زبان لوکزامبورگی|لوکزامبورگی]]')
  s.sub!(/\[\[w:(Welsh language\|Welsh)\]\]/i, '[[w:fa:زبان ولزی|ولزی]]')
  s.sub!(/\[\[w:(Albanian language\|Albanian)\]\]/i, '[[w:fa:زبان آلبانیایی|آلبانیایی]]')
  s.sub!(/\[\[w:(Bosnian language\|Bosnian)\]\]/i, '[[w:fa:زبان بوسنیایی|بوسنیایی]]')
  s.sub!(/\[\[w:(Icelandic language\|Icelandic)\]\]/i, '[[w:fa:زبان ایسلندی|ایسلندی]]')
  s.sub!(/\[\[w:(Tamil language\|Tamil)\]\]/i, '[[w:fa:زبان تامیلی|تامیلی]]')
  s.sub!(/\[\[w:(Belarusian language\|Belarusian)\]\]/i, '[[w:fa:زبان بلاروسی|بلاروسی]]')
  s.sub!(/\[\[w:(Aragonese language\|Aragonese)\]\]/i, '[[w:fa:زبان آراگونی|آراگونی]]')
  s.sub!(/\[\[w:(Occitan language\|Occitan)\]\]/i, '[[w:fa:زبان اکسیتان|اکسیتان]]')
  s.sub!(/\[\[w:(Bengali language\|Bengali)\]\]/i, '[[w:fa:زبان بنگالی|بنگالی]]')
  s.sub!(/\[\[w:(Ido language\|Ido)\]\]/i, '[[w:fa:زبان ایدو|ایدو]]')
  s.sub!(/\[\[w:(Swahili language\|Swahili)\]\]/i, '[[w:fa:زبان سواحیلی|سواحیلی]]')
  s.sub!(/\[\[w:(Gujarati language\|Gujarati)\]\]/i, '[[w:fa:زبان گجراتی|گجراتی]]')
  s.sub!(/\[\[w:(Malayalam language\|Malayalam)\]\]/i, '[[w:fa:زبان مالایالم|مالایالم]]')
  s.sub!(/\[\[w:(Afrikaans language\|Afrikaans)\]\]/i, '[[w:fa:زبان آفریکانس|آفریکانس]]')
  s.sub!(/\[\[w:(Sicilian language\|Sicilian)\]\]/i, '[[w:fa:زبان سیسیلی|سیسیلی]]')
  s.sub!(/\[\[w:(Urdu language\|Urdu)\]\]/i, '[[w:fa:زبان اردو|اردو]]')
  s.sub!(/\[\[w:(Kurdish language\|Kurdish)\]\]/i, '[[w:fa:زبان کردی|کردی]]')
  s.sub!(/\[\[w:(Sundanese language\|Sundanese)\]\]/i, '[[w:fa:زبان سوندایی|سوندایی]]')
  s.sub!(/\[\[w:(Armenian language\|Armenian)\]\]/i, '[[w:fa:زبان ارمنی|ارمنی]]')
  s.sub!(/\[\[w:(Irish language\|Irish)\]\]/i, '[[w:fa:زبان ایرلندی|ایرلندی]]')
  s.sub!(/\[\[w:(Chuvash language\|Chuvash)\]\]/i, '[[w:fa:زبان چوواشی|چوواشی]]')
  s.sub!(/\[\[w:(Nepali language\|Nepali)\]\]/i, '[[w:fa:زبان نپالی|نپالی]]')
  s.sub!(/\[\[w:(Kannada language\|Kannada)\]\]/i, '[[w:fa:زبان کانارا|کانارا]]')
  s.sub!(/\[\[w:(Tajik language\|Tajik)\]\]/i, '[[w:fa:زبان تاجیکی|تاجیکی]]')
  s.sub!(/\[\[w:(Kazakh language\|Kazakh)\]\]/i, '[[w:fa:زبان قزاقی|قزاقی]]')
  s.sub!(/\[\[w:(Tatar language\|Tatar)\]\]/i, '[[w:fa:زبان تاتاری|تاتاری]]')
  s.sub!(/\[\[w:(Yiddish language\|Yiddish)\]\]/i, '[[w:fa:زبان ییدیش|ییدیش]]')
  s.sub!(/\[\[w:(Alemannic language\|Alemannic)\]\]/i, '[[w:fa:زبان آلمانیش|آلمانیش]]')
  s.sub!(/\[\[w:(Scottish Gaelic language\|Scottish Gaelic)\]\]/i, '[[w:fa:زبان گالیک اسکاتلندی|گالیک اسکاتلندی]]')
  s.sub!(/\[\[w:(Ossetian language\|Ossetian)\]\]/i, '[[w:fa:زبان آسی|آسی]]')
  s.sub!(/\[\[w:(Uzbek language\|Uzbek)\]\]/i, '[[w:fa:زبان ازبکی|ازبکی]]')
  s.sub!(/\[\[w:(Sakha language\|Sakha)\]\]/i, '[[w:fa:زبان یاکوتی|یاکوتی]]')
  s.sub!(/\[\[w:(Egyptian Arabic language\|Egyptian Arabic)\]\]/i, '[[w:fa:زبان عربی مصری|عربی مصری]]')
  s.sub!(/\[\[w:(Amharic language\|Amharic)\]\]/i, '[[w:fa:زبان امهری|امهری]]')
  s.sub!(/\[\[w:(Maori language\|Maori)\]\]/i, '[[w:fa:زبان مائوری|مائوری]]')
  s.sub!(/\[\[w:(Corsican language\|Corsican)\]\]/i, '[[w:fa:زبان کرسی|کرسی]]')
  s.sub!(/\[\[w:(Gilaki language\|Gilaki)\]\]/i, '[[w:fa:زبان گیلکی|گیلکی]]')
  s.sub!(/\[\[w:(Mongolian language\|Mongolian)\]\]/i, '[[w:fa:زبان مغولی|مغولی]]')
  s.sub!(/\[\[w:(Interlingua language\|Interlingua)\]\]/i, '[[w:fa:زبان اینترلینگوا|اینترلینگوا]]')
  s.sub!(/\[\[w:(Burmese language\|Burmese)\]\]/i, '[[w:fa:زبان برمه‌ای|برمه‌ای]]')
  s.sub!(/\[\[w:(Faroese language\|Faroese)\]\]/i, '[[w:fa:زبان فاروئی|فاروئی]]')
  s.sub!(/\[\[w:(Sinhalese language\|Sinhalese)\]\]/i, '[[w:fa:زبان سینهالی|سینهالی]]')
  s.sub!(/\[\[w:(Turkmen language\|Turkmen)\]\]/i, '[[w:fa:زبان ترکمنی|ترکمنی]]')
  s.sub!(/\[\[w:(Sanskrit language\|Sanskrit)\]\]/i, '[[w:fa:زبان سانسکریت|سانسکریت]]')
  s.sub!(/\[\[w:(Manx language\|Manx)\]\]/i, '[[w:fa:زبان مانکس|مانکس]]')
  s.sub!(/\[\[w:(Divehi language\|Divehi)\]\]/i, '[[w:fa:زبان دیوهی|دیوهی]]')
  s.sub!(/\[\[w:(Sorani language\|Sorani)\]\]/i, '[[w:fa:زبان سورانی|سورانی]]')
  s.sub!(/\[\[w:(Zazaki language\|Zazaki)\]\]/i, '[[w:fa:زبان زازاکی|زازاکی]]')
  s.sub!(/\[\[w:(Romansh language\|Romansh)\]\]/i, '[[w:fa:زبان رومانش|رومانش]]')
  s.sub!(/\[\[w:(Mazandarani language\|Mazandarani)\]\]/i, '[[w:fa:زبان مازندرانی|مازندرانی]]')
  s.sub!(/\[\[w:(Uyghur language\|Uyghur)\]\]/i, '[[w:fa:زبان اویغوری|اویغوری]]')
  s.sub!(/\[\[w:(Maltese language\|Maltese)\]\]/i, '[[w:fa:زبان مالتی|مالتی]]')
  s.sub!(/\[\[w:(Tibetan language\|Tibetan)\]\]/i, '[[w:fa:زبان تبتی|تبتی]]')
  s.sub!(/\[\[w:(Anglo-Saxon language\|Anglo-Saxon)\]\]/i, '[[w:fa:زبان انگلیسی باستان|انگلیسی باستان]]')
  s.sub!(/\[\[w:(Novial language\|Novial)\]\]/i, '[[w:fa:زبان نوویال|نوویال]]')
  s.sub!(/\[\[w:(Kashubian language\|Kashubian)\]\]/i, '[[w:fa:زبان کاشوبی|کاشوبی]]')
  s.sub!(/\[\[w:(Sardinian language\|Sardinian)\]\]/i, '[[w:fa:زبان ساردنیایی|ساردنیایی]]')
  s.sub!(/\[\[w:(Ladino language\|Ladino)\]\]/i, '[[w:fa:زبان لادینو|لادینو]]')
  s.sub!(/\[\[w:(Khmer language\|Khmer)\]\]/i, '[[w:fa:زبان خمر|خمر]]')
  s.sub!(/\[\[w:(Pashto language\|Pashto)\]\]/i, '[[w:fa:زبان پشتو|پشتو]]')
  s.sub!(/\[\[w:(Cornish language\|Cornish)\]\]/i, '[[w:fa:زبان کورنی|کورنی]]')
  s.sub!(/\[\[w:(Ripuarian language\|Ripuarian)\]\]/i, '[[w:fa:زبان ریپواری|ریپواری]]')
  s.sub!(/\[\[w:(Punjabi language\|Punjabi)\]\]/i, '[[w:fa:زبان پنجابی|پنجابی]]')
  s.sub!(/\[\[w:(Silesian language\|Silesian)\]\]/i, '[[w:fa:زبان سیلزیایی|سیلزیایی]]')
  s.sub!(/\[\[w:(Tongan language\|Tongan)\]\]/i, '[[w:fa:زبان تونگایی|تونگایی]]')
  s.sub!(/\[\[w:(Karachay\-Balkar language\|Karachay\-Balkar)\]\]/i, '[[w:fa:زبان کاراچایی-بالکاری|کاراچایی-بالکاری]]')
  s.sub!(/\[\[w:(Crimean Tatar language\|Crimean Tatar)\]\]/i, '[[w:fa:زبان تاتاری کریمه|تاتاری کریمه]]')
  s.sub!(/\[\[w:(Kirghiz language\|Kirghiz)\]\]/i, '[[w:fa:زبان قرقیزی|قرقیزی]]')
  s.sub!(/\[\[w:(Bashkir language\|Bashkir)\]\]/i, '[[w:fa:زبان باشقیری|باشقیری]]')
  s.sub!(/\[\[w:(Wolof language\|Wolof)\]\]/i, '[[w:fa:زبان ولوف|ولوف]]')
  s.sub!(/\[\[w:(Greenlandic language\|Greenlandic)\]\]/i, '[[w:fa:زبان گرینلندی|گرینلندی]]')
  s.sub!(/\[\[w:(Gagauz language\|Gagauz)\]\]/i, '[[w:fa:زبان گاگاووز|گاگاووز]]')
  s.sub!(/\[\[w:(Abkhazian language\|Abkhazian)\]\]/i, '[[w:fa:زبان آبخازی|آبخازی]]')
  s.sub!(/\[\[w:(Avar language\|Avar)\]\]/i, '[[w:fa:زبان آواری|آواری]]')
  s.sub!(/\[\[w:(Romani language\|Romani)\]\]/i, '[[w:fa:زبان رومانی|رومانی]]')
  s.sub!(/\[\[w:(Karakalpak language\|Karakalpak)\]\]/i, '[[w:fa:زبان قره‌قالپاقی|قره‌قالپاقی]]')
  s.sub!(/\[\[w:(Moldovan language\|Moldovan)\]\]/i, '[[w:fa:زبان مولداویایی|مولداویایی]]')
  s.sub!(/\[\[w:(Kashmiri language\|Kashmiri)\]\]/i, '[[w:fa:زبان کشمیری|کشمیری]]')
  s.sub!(/\[\[w:(Bislama language\|Bislama)\]\]/i, '[[w:fa:زبان بیسلاما|بیسلاما]]')
  s.sub!(/\[\[w:(Assamese language\|Assamese)\]\]/i, '[[w:fa:زبان آسامی|آسامی]]')
  s.sub!(/\[\[w:(Inuktitut language\|Inuktitut)\]\]/i, '[[w:fa:زبان اینوکتیتوت|اینوکتیتوت]]')
  s.sub!(/\[\[w:(Tigrinya language\|Tigrinya)\]\]/i, '[[w:fa:زبان تیگرینیایی|تیگرینیایی]]')
  s.sub!(/\[\[w:(Dzongkha language\|Dzongkha)\]\]/i, '[[w:fa:زبان دزونگخا|دزونگخا]]')
  s.sub!(/\[\[w:(Xhosa language\|Xhosa)\]\]/i, '[[w:fa:زبان خوسایی|خوسایی]]')
  s.sub!(/\[\[w:(Kanuri language\|Kanuri)\]\]/i, '[[w:fa:زبان کنوری|کنوری]]')
  s.sub!(/\[\[w:(Herero language\|Herero)\]\]/i, '[[w:fa:زبان هررو|هررو]]')
  s.sub!(/\[\[w:(Sindhi language\|Sindhi)\]\]/i, '[[w:fa:زبان سندی|سندی]]')
  s.sub!(/\[\[w:(Norwegian \(Bokm\&\#229\;l\) language\|Norwegian \(Bokm\&\#229\;l\))\]\]/i, '[[w:fa:زبان نروژی|نروژی (بوکمال)]]')
  s.sub!(/\[\[w:(Mirandese language\|Mirandese)\]\]/i, '[[w:fa:زبان میراندی|میراندی]]')
  s.sub!(/\[\[w:(Latgalian language\|Latgalian)\]\]/i, '[[w:fa:زبان لاتگالی|لاتگالی]]')
  s.sub!(/\[\[w:(Kabardian Circassian language\|Kabardian Circassian)\]\]/i, '[[w:fa:زبان کاباردی|کاباردی]]')
  s.sub!(/\[\[w:(Gothic language\|Gothic)\]\]/i, '[[w:fa:زبان گوتیک|گوتیک]]')
  s.sub!(/\[\[w:(Buryat \(Russia\) language\|Buryat \(Russia\))\]\]/i, '[[w:fa:زبان بوریاتی|بوریاتی]]')
  s.sub!(/\[\[w:(Zulu language\|Zulu)\]\]/i, '[[w:fa:زبان زولو|زولو]]')
  s.sub!(/\[\[w:(Udmurt language\|Udmurt)\]\]/i, '[[w:fa:زبان اودمورت|اودمورت]]')
  s.sub!(/\[\[w:(Friulian language\|Friulian)\]\]/i, '[[w:fa:زبان فریولی|فریولی]]')
  s.sub!(/\[\[w:(Komi language\|Komi)\]\]/i, '[[w:fa:زبان کومی|کومی]]')
  s.sub!(/\[\[w:(Franco\-Provençal\/Arpitan language\|Franco\-Provençal\/Arpitan)\]\]/i, '[[w:fa:زبان آرپیتان|آرپیتان]]')
  s.sub!(/\[\[w:(Extremaduran language\|Extremaduran)\]\]/i, '[[w:fa:زبان اکسترامادورایی|اکسترامادورایی]]')
  s.sub!(/\[\[w:(Kalmyk language\|Kalmyk)\]\]/i, '[[w:fa:زبان قالمیق|قالمیق]]')
  s.sub!(/\[\[w:(Picard language\|Picard)\]\]/i, '[[w:fa:زبان پیکاردی|پیکاردی]]')
  s.sub!(/\[\[w:(Erzya language\|Erzya)\]\]/i, '[[w:fa:زبان ارزیا|ارزیا]]')
  s.sub!(/\[\[w:(Emilian\-Romagnol language\|Emilian\-Romagnol)\]\]/i, '[[w:fa:زبان امیلیانو-رومانیولو|امیلیانو-رومانیولو]]')
  s.sub!(/\[\[w:(Assyrian Neo\-Aramaic language\|Assyrian Neo\-Aramaic)\]\]/i, '[[w:fa:زبان آشوری|آشوری]]')
  s.sub!(/\[\[w:(Chechen language\|Chechen)\]\]/i, '[[w:fa:زبان چچنی|چچنی]]')
  s.sub!(/\[\[w:(Moksha language\|Moksha)\]\]/i, '[[w:fa:زبان موکشا|موکشا]]')
  s.sub!(/\[\[w:(Norman language\|Norman)\]\]/i, '[[w:fa:زبان نورمان|نورمان]]')
  s.sub!(/\[\[w:(Venetian language\|Venetian)\]\]/i, '[[w:fa:زبان ونتی|ونتی]]')
  s.sub!(/\[\[w:(Nahuatl language\|Nahuatl)\]\]/i, '[[w:fa:زبان ناهواتل|ناهواتل]]')
  s.sub!(/\[\[w:(Asturian language\|Asturian)\]\]/i, '[[w:fa:زبان آستوریایی|آستوریایی]]')
  s.sub!(/\[\[w:(Neapolitan language\|Neapolitan)\]\]/i, '[[w:fa:زبان ناپولی|ناپولی]]')
  s.sub!(/\[\[w:(Samogitian language\|Samogitian)\]\]/i, '[[w:fa:زبان ساموگیتی|ساموگیتی]]')
  s.sub!(/\[\[w:(Walloon language\|Walloon)\]\]/i, '[[w:fa:زبان والونی|والونی]]')
  s.sub!(/\[\[w:(Piedmontese language\|Piedmontese)\]\]/i, '[[w:fa:زبان پیدمونتی|پیدمونتی]]')
  s.sub!(/\[\[w:(Lombard language\|Lombard)\]\]/i, '[[w:fa:زبان لومبارد|لومبارد]]')
  s.sub!(/\[\[w:(Quechua language\|Quechua)\]\]/i, '[[w:fa:کچوآ|کچوآ]]')
  s.sub!(/\[\[w:(Aromanian language\|Aromanian)\]\]/i, '[[w:fa:زبان آرومانی|آرومانی]]')
  s.sub!(/\[\[w:(Waray\-Waray language\|Waray\-Waray)\]\]/i, '[[w:fa:زبان وینارایی|وینارایی]]')
  s.sub!(/\[\[w:(Norwegian \(Nynorsk\) language\|Norwegian \(Nynorsk\))\]\]/i, '[[w:fa:زبان نینورسک|نینورسک]]')
  s.sub!(/\[\[w:(Newar \/ Nepal Bhasa language\|Newar \/ Nepal Bhasa)\]\]/i, '[[w:fa:زبان نپال بهاسایی|نپال بهاسایی]]')
  s.sub!(/\[\[w:(Haitian language\|Haitian)\]\]/i, '[[w:fa:زبان کریول آییسینی|کریول آییسینی]]')
  s.sub!(/\[\[w:(Cebuano language\|Cebuano)\]\]/i, '[[w:fa:زبان سینوگبانونی|سینوگبانونی]]')
  s.sub!(/\[\[w:(Malagasy language\|Malagasy)\]\]/i, '[[w:fa:زبان مالاگاسی|مالاگاسی]]')
  s.sub!(/\[\[w:(Yoruba language\|Yoruba)\]\]/i, '[[w:fa:زبان یوروبایی|یوروبایی]]')
  s.sub!(/\[\[w:(West Frisian language\|West Frisian)\]\]/i, '[[w:fa:زبان فریسکی|فریسکی]]')
  s.sub!(/\[\[w:(Western Panjabi language\|Western Panjabi)\]\]/i, '[[w:fa:زبان شاه مکهی پنجابی|شاه مکهی پنجابی]]')
  s.sub!(/\[\[w:(Low Saxon language\|Low Saxon)\]\]/i, '[[w:fa:زبان آلمانی سفلای غربی |آلمانی سفلای غربی ]]')
  s.sub!(/\[\[w:(Scots language\|Scots)\]\]/i, '[[w:fa:زبان اسکاتس|اسکاتس]]')
  s.sub!(/\[\[w:(Bavarian language\|Bavarian)\]\]/i, '[[w:fa:زبان اتریشی-باواریایی|اتریشی-باواریایی]]')
  s.sub!(/\[\[w:(West Flemish language\|West Flemish)\]\]/i, '[[w:fa:زبان فلاندری غربی|فلاندری غربی]]')
  s.sub!(/\[\[w:(Wu language\|Wu)\]\]/i, '[[w:fa:زبان وو|وو]]')
  s.sub!(/\[\[w:(Zeelandic language\|Zeelandic)\]\]/i, '[[w:fa:زبان زیلاندی|زیلاندی]]')
  s.sub!(/\[\[w:(Franco\-Proven\çal\/Arpitan language\|Franco\-Proven\çal\/Arpitan)\]\]/i, '[[w:fa:زبان آرپیتان|آرپیتان]]')
  s.sub!(/\[\[w:(Saterland Frisian language\|Saterland Frisian)\]\]/i, '[[w:fa:زبان فریسی ساترلند|فریسی ساترلند]]')
  s.sub!(/\[\[w:(North Frisian language\|North Frisian)\]\]/i, '[[w:fa:زبان فریسی شمالی|فریسی شمالی]]')
  s.sub!(/\[\[w:(Bambara language\|Bambara)\]\]/i, '[[w:fa:زبان بامبارایی|بامبارایی]]')
  s.sub!(/\[\[w:(Vepsian language\|Vepsian)\]\]/i, '[[w:fa:زبان وپس|وپس]]')
  s.sub!(/\[\[w:(Sesotho language\|Sesotho)\]\]/i, '[[w:fa:زبان سوتو|سوتو]]')
end
